### ISSUE TITLE
[2.0.0-M6] NoSuchElementException with a documented json""""" example.

### ISSUE THREAD

**Issue by ScalaWilliam** [propensive/rapture#196]
![screen shot 2016-05-28 at 11 46 46](https://cloud.githubusercontent.com/assets/2464813/15624969/e3ff4cb8-24c9-11e6-971c-924a3c0a98a9.png)

BrokenApp.scala:

``` scala
import rapture.json._
import rapture.json.jsonBackends.play._

object BrokenApp extends App {
  val f = "apple"
  val q =
    json"""{
  "fruit": $f,
  "variants": ${List("cox", "braeburn")}
}"""
}

```

```
> runMain BrokenApp
[info] Running BrokenApp 
[error] (run-main-1c) java.util.NoSuchElementException: None.get
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:347)
        at scala.None$.get(Option.scala:345)
        at BrokenApp$.delayedEndpoint$BrokenApp$1(BrokenApp.scala:6)
        at BrokenApp$delayedInit$body.apply(BrokenApp.scala:4)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at BrokenApp$.main(BrokenApp.scala:4)
        at BrokenApp.main(BrokenApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
[error] (compile:runMain) Nonzero exit code: 1
[error] Total time: 0 s, completed 28-May-2016 11:43:44
```

build.sbt:

``` scala
scalaVersion := "2.11.7"
libraryDependencies += json
libraryDependencies += "com.propensive" %% "rapture" % "2.0.0-M6"
libraryDependencies += "com.propensive" %% "rapture-json-play" % "2.0.0-M6"
```

project/build.properties:

```
sbt.version=0.13.11
```

project/plugins.sbt:

``` scala
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.3")
```

**Comment by propensive** [comment]
Thanks for the really clear report, @ScalaWilliam! It looks like issue #197, which I've just fixed. Re-tested your example, and it seems to work. :)
